name: learning
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  hive_ce_flutter: ^2.3.3
  json_annotation: ^4.9.0
  firebase_core: ^4.2.0
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  talker_flutter: ^5.0.2
  intl: ^0.20.2
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  dio: ^5.9.0
  flutter_svg: ^2.2.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  hive_ce_generator: ^1.10.0
  json_serializable: ^6.11.1
  build_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/svg/
     - assets/images/placeholder.png

